# Generated by Django 6.0.6 on 2026-06-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.role')),
            ],
        ),
    ]
