# Generated by Django 6.0.6 on 2026-07-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('interview', 'question'), name='unique_answer_per_question'),
        ),
    ]
